export interface Course {
  id: string
  slug: string
  name: string
  category: "geral" | "tecnico" | "saude"
  categoryLabel: string
  description: string
  shortDescription: string
  classes: string[]
  monthlyFee: string
  enrollmentFee: string
  duration: string
  jobMarket: string[]
  requirements: string[]
  documents: string[]
  careerPath: string
  highlights: string[]
  topics: string[]
}

export const coursesData: Course[] = [
  {
    id: "ensino-primario",
    slug: "ensino-primario",
    name: "Ensino Primário",
    category: "geral",
    categoryLabel: "Ensino Geral Diurno",
    shortDescription: "Educação fundamental com foco em leitura, escrita, matemática e desenvolvimento integral.",
    description:
      "O Ensino Primário oferece educação fundamental de qualidade, desenvolvendo competências essenciais em leitura, escrita, matemática e ciências. Com uma abordagem pedagógica focada no desenvolvimento integral do aluno, preparamos crianças para o sucesso académico e pessoal.",
    classes: ["Iniciação", "1ª", "2ª", "3ª", "4ª", "5ª", "6ª"],
    monthlyFee: "A partir de 20.000,00 Kz/mês",
    enrollmentFee: "15.000,00 Kz",
    duration: "6 anos",
    jobMarket: [],
    requirements: [
      "Certificado de habilitações literárias",
      "Fotocópia da cédula/bilhete de identidade",
      "Cartão de vacina actualizado",
      "Atestado médico",
      "4 fotografias tipo passe",
    ],
    documents: [
      "Bilhete de Identidade",
      "Certificado anterior",
      "Comprovativo de residência",
    ],
    careerPath: "Preparação para o I Ciclo do Ensino Secundário",
    highlights: [
      "Metodologia inovadora e interativa",
      "Ensino de inglês desde a Iniciação",
      "Educação Física e Artística integradas",
      "Ambiente seguro e acolhedor",
      "Merenda e transporte gratuitos até à 2ª classe",
    ],
    topics: [
      "Português",
      "Matemática",
      "Ciências Naturais",
      "Estudo do Meio",
      "Inglês",
      "Educação Física",
      "Artes Plásticas",
      "Música",
    ],
  },
  {
    id: "i-ii-ciclos",
    slug: "i-ii-ciclos-ensino-secundario",
    name: "I e II Ciclos do Ensino Secundário",
    category: "geral",
    categoryLabel: "Ensino Geral Diurno",
    shortDescription: "Preparação académica sólida para o ensino superior e mercado de trabalho (7º-9º classes).",
    description:
      "Os ciclos I e II do Ensino Secundário preparam os alunos académica e profissionalmente, oferecendo uma educação abrangente que combina disciplinas teóricas com orientação vocacional. Ao final do 9º ano, os alunos estarão preparados para prosseguir com confiança para o ensino técnico ou superior.",
    classes: ["7ª", "8ª", "9ª"],
    monthlyFee: "29.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "3 anos",
    jobMarket: [],
    requirements: [
      "Certificado de habilitações literárias da 6ª classe",
      "Fotocópia da cédula/bilhete de identidade",
      "Cartão de vacina actualizado",
      "Atestado médico",
      "4 fotografias tipo passe",
    ],
    documents: [
      "Boletim de notas do ano anterior",
      "Comprovativo de residência",
      "Referência escolar",
    ],
    careerPath: "Acesso ao Ensino Técnico Médio ou Ensino Geral Superior",
    highlights: [
      "Orientação Vocacional na 9ª classe",
      "Laboratórios de Ciências bem equipados",
      "Preparação para exames nacionais",
      "Acompanhamento pedagógico personalizado",
      "Projectos interdisciplinares",
    ],
    topics: [
      "Português",
      "Inglês",
      "Francês",
      "Matemática",
      "Física",
      "Química",
      "Biologia",
      "História",
      "Geografia",
      "Educação Física",
      "Informática",
    ],
  },
  {
    id: "tecnico-informatica",
    slug: "tecnico-informatica",
    name: "Técnico Médio de Informática",
    category: "tecnico",
    categoryLabel: "Ensino Técnico Médio",
    shortDescription: "Formação em sistemas, programação e tecnologias da informação.",
    description:
      "O curso de Técnico Médio de Informática oferece formação prática e teórica em programação, sistemas de informação, redes e suporte técnico. Prepara profissionais para atuar no mercado das tecnologias da informação, um sector em crescimento exponencial.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 32.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Técnico de Sistemas",
      "Programador",
      "Administrador de Redes",
      "Técnico de Suporte",
      "Analista de Sistemas",
    ],
    requirements: [
      "Conclusão do 9º ano (ou equivalente)",
      "Conhecimentos básicos de matemática",
      "Aptidão para a área técnica",
    ],
    documents: [
      "Certificado do 9º ano",
      "Atestado de capacidade física",
      "Fotocópias de documentos de identificação",
    ],
    careerPath: "Técnico de Sistemas / Programador / Administrador de Redes",
    highlights: [
      "Laboratórios de Informática modernos",
      "Licenças de software profissional",
      "Projectos com empresas locais",
      "Estágio profissional incluso",
      "Certificações técnicas reconhecidas",
    ],
    topics: [
      "Programação em Python",
      "Desenvolvimento Web",
      "Redes de Computadores",
      "Administração de Sistemas",
      "Segurança Informática",
      "Base de Dados",
      "Suporte Técnico",
      "Projetos Práticos",
    ],
  },
  {
    id: "tecnico-electronica",
    slug: "tecnico-electronica",
    name: "Técnico Médio de Electrónica",
    category: "tecnico",
    categoryLabel: "Ensino Técnico Médio",
    shortDescription: "Especialização em electrónica, automação e instalações eléctricas.",
    description:
      "Formação especializada em electrónica, circuitos, automação industrial e instalações eléctricas. Os alunos desenvolvem competências práticas para manutenção, reparação e instalação de equipamentos electrónicos em diversos contextos profissionais.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 32.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Técnico de Electrónica",
      "Electricista Especializado",
      "Técnico de Manutenção",
      "Instalador de Sistemas",
      "Técnico de Automação",
    ],
    requirements: [
      "Conclusão do 9º ano",
      "Conhecimentos de física e matemática",
      "Aptidão para trabalho prático",
    ],
    documents: [
      "Certificado do 9º ano",
      "Atestado de capacidade física e mental",
      "Fotocópias de documentos",
    ],
    careerPath: "Técnico Especializado / Supervisor Técnico",
    highlights: [
      "Oficinas bem equipadas",
      "Simuladores de circuitos profissionais",
      "Parcerias com empresas do sector",
      "Certificação técnica",
      "Oportunidades de emprego imediato",
    ],
    topics: [
      "Princípios de Electrónica",
      "Circuitos Digitais",
      "Instrumentação",
      "Instalações Eléctricas",
      "Automação Industrial",
      "Manutenção Preventiva",
      "Segurança Profissional",
      "Projetos Práticos",
    ],
  },
  {
    id: "telecomunicacoes",
    slug: "telecomunicacoes",
    name: "Telecomunicações",
    category: "tecnico",
    categoryLabel: "Ensino Técnico Médio",
    shortDescription: "Formação em sistemas de telecomunicações e redes.",
    description:
      "Especialização em sistemas de telecomunicações, infraestruturas de rede e comunicações móveis. Prepara técnicos para operar, manter e gerir sistemas de telecomunicações modernos.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 32.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Técnico de Telecomunicações",
      "Técnico de Redes",
      "Operador de Centro de Controlo",
      "Técnico de Manutenção",
      "Especialista em Conectividade",
    ],
    requirements: [
      "Conclusão do 9º ano",
      "Conhecimentos técnicos básicos",
      "Interesse em tecnologias de comunicação",
    ],
    documents: [
      "Certificado do 9º ano",
      "Atestado médico",
      "Fotocópias de documentos",
    ],
    careerPath: "Técnico de Telecomunicações / Gestor de Infraestruturas",
    highlights: [
      "Laboratórios de telecomunicações",
      "Tecnologia de ponta",
      "Parcerias com operadores móveis",
      "Certificações internacionais",
      "Mercado de trabalho competitivo",
    ],
    topics: [
      "Sistemas de Telecomunicações",
      "Redes Móveis",
      "Infraestruturas de Comunicação",
      "Fibra Óptica",
      "Sistemas Digitais",
      "Manutenção de Redes",
      "Projetos de Conectividade",
      "Segurança em Telecomunicações",
    ],
  },
  {
    id: "gestao-recursos-humanos",
    slug: "gestao-recursos-humanos",
    name: "Gestão de Recursos Humanos",
    category: "tecnico",
    categoryLabel: "Ensino Técnico Médio",
    shortDescription: "Preparação para gestão de pessoas e recursos humanos nas organizações.",
    description:
      "Formação em gestão de pessoas, administração de pessoal, relações laborais e desenvolvimento organizacional. Prepara profissionais para actuar em departamentos de Recursos Humanos de empresas públicas e privadas.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 32.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Técnico de Recursos Humanos",
      "Assistente de Pessoal",
      "Coordenador de RH",
      "Especialista em Recrutamento",
      "Gestor de Talentos",
    ],
    requirements: [
      "Conclusão do 9º ano",
      "Aptidão para comunicação",
      "Interesse em gestão",
    ],
    documents: [
      "Certificado do 9º ano",
      "Referências pessoais",
      "Fotocópias de documentos",
    ],
    careerPath: "Técnico de RH / Gerente de Recursos Humanos",
    highlights: [
      "Formação em legislação laboral",
      "Simulações de casos reais",
      "Estágio em empresas",
      "Desenvolvimento de soft skills",
      "Oportunidades de liderança",
    ],
    topics: [
      "Gestão de Pessoal",
      "Legislação Laboral",
      "Recrutamento e Selecção",
      "Avaliação de Desempenho",
      "Desenvolvimento de Competências",
      "Relações Industriais",
      "Administração de Pessoal",
      "Comunicação Corporativa",
    ],
  },
  {
    id: "contabilidade-e-gestao",
    slug: "contabilidade-e-gestao",
    name: "Contabilidade e Gestão",
    category: "tecnico",
    categoryLabel: "Ensino Técnico Médio",
    shortDescription: "Formação em contabilidade, finanças e gestão empresarial.",
    description:
      "O curso de Contabilidade e Gestão oferece formação sólida em contabilidade, finanças, fiscalidade e administração de empresas. Prepara profissionais capazes de gerir recursos financeiros, elaborar demonstrações contabilísticas e apoiar a tomada de decisão em organizações públicas e privadas.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 32.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Técnico de Contabilidade",
      "Assistente Financeiro",
      "Analista de Gestão",
      "Técnico de Tesouraria",
      "Auxiliar de Auditoria",
    ],
    requirements: [
      "Conclusão do 9º ano",
      "Aptidão para a matemática",
      "Interesse em gestão e finanças",
    ],
    documents: [
      "Certificado do 9º ano",
      "Referências pessoais",
      "Fotocópias de documentos",
    ],
    careerPath: "Técnico de Contabilidade / Gestor Financeiro",
    highlights: [
      "Formação em software de contabilidade",
      "Simulações de gestão empresarial",
      "Estágio em empresas",
      "Noções de fiscalidade angolana",
      "Oportunidades no sector público e privado",
    ],
    topics: [
      "Contabilidade Geral",
      "Contabilidade Analítica",
      "Gestão Financeira",
      "Fiscalidade",
      "Gestão de Empresas",
      "Economia",
      "Matemática Financeira",
      "Auditoria",
    ],
  },
  {
    id: "enfermagem",
    slug: "enfermagem",
    name: "Enfermagem",
    category: "saude",
    categoryLabel: "Ensino Técnico Médio de Saúde",
    shortDescription: "Formação técnica profissional em cuidados de saúde com prática clínica.",
    description:
      "Curso de Enfermagem oferece formação completa em cuidados de saúde, procedimentos clínicos, ética profissional e atendimento ao paciente. Com ênfase na prática clínica supervisionada, prepara enfermeiros competentes para actuar em hospitais e centros de saúde.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 20.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Enfermeiro Hospitalar",
      "Enfermeiro de Centro de Saúde",
      "Enfermeiro de Cuidados Domiciliários",
      "Supervisor de Ala",
      "Gestor de Saúde",
    ],
    requirements: [
      "Conclusão do 9º ano",
      "Vocação para saúde",
      "Capacidade física e emocional",
      "Atestado médico completo",
    ],
    documents: [
      "Certificado do 9º ano",
      "Atestado de capacidade física",
      "Vacinas obrigatórias",
      "Teste HIV",
      "Fotocópias de documentos",
    ],
    careerPath: "Enfermeiro / Supervisor de Saúde / Gestor Hospitalar",
    highlights: [
      "Clínicas e laboratórios bem equipados",
      "Prática clínica em hospitais reais",
      "Supervisores experientes",
      "Certificação profissional",
      "Emprego garantido após conclusão",
    ],
    topics: [
      "Anatomia e Fisiologia",
      "Farmacologia",
      "Procedimentos Clínicos",
      "Cuidados ao Paciente",
      "Higiene e Segurança",
      "Ética Profissional",
      "Prática Clínica Supervisionada",
      "Emergências Médicas",
    ],
  },
  {
    id: "analises-clinicas",
    slug: "analises-clinicas",
    name: "Análises Clínicas",
    category: "saude",
    categoryLabel: "Ensino Técnico Médio de Saúde",
    shortDescription: "Capacitação em análises laboratoriais e diagnóstico clínico.",
    description:
      "Formação especializada em técnicas de laboratório, análise de amostras biológicas e interpretação de resultados. Prepara técnicos para trabalhar em laboratórios clínicos, hospitais e centros de diagnóstico.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 20.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Técnico de Laboratório",
      "Analista Clínico",
      "Técnico de Diagnóstico",
      "Supervisor de Laboratório",
      "Gestor de Qualidade",
    ],
    requirements: [
      "Conclusão do 9º ano",
      "Conhecimento em Ciências",
      "Precisão e atenção aos detalhes",
    ],
    documents: [
      "Certificado do 9º ano",
      "Atestado médico",
      "Vacinas obrigatórias",
      "Fotocópias de documentos",
    ],
    careerPath: "Técnico de Laboratório / Supervisor / Especialista em Diagnóstico",
    highlights: [
      "Laboratórios modernos e equipados",
      "Equipamento de análise de ponta",
      "Prática com amostras reais",
      "Certificações técnicas",
      "Oportunidades de especialização",
    ],
    topics: [
      "Técnicas de Laboratório",
      "Hematologia",
      "Bioquímica Clínica",
      "Microbiologia",
      "Parasitologia",
      "Uroanálise",
      "Controle de Qualidade",
      "Segurança Biológica",
    ],
  },
  {
    id: "farmacia",
    slug: "farmacia",
    name: "Farmácia",
    category: "saude",
    categoryLabel: "Ensino Técnico Médio de Saúde",
    shortDescription: "Formação em gestão farmacêutica e medicamentos.",
    description:
      "Curso de Farmácia oferece conhecimentos em medicamentos, gestão farmacêutica, manipulação de fármacos e atendimento ao público. Prepara técnicos para trabalhar em farmácias, hospitais e indústria farmacêutica.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 20.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Técnico Farmacêutico",
      "Gerente de Farmácia",
      "Representante Farmacêutico",
      "Técnico de Armazém",
      "Especialista em Medicamentos",
    ],
    requirements: [
      "Conclusão do 9º ano",
      "Conhecimentos em Química",
      "Seriedade profissional",
    ],
    documents: [
      "Certificado do 9º ano",
      "Atestado médico",
      "Antecedentes criminais (certidão)",
      "Fotocópias de documentos",
    ],
    careerPath: "Técnico Farmacêutico / Gerente de Farmácia / Especialista",
    highlights: [
      "Laboratório farmacêutico",
      "Armários com medicamentos variados",
      "Formação em farmacocinética",
      "Legislação farmacêutica",
      "Oportunidades em indústria",
    ],
    topics: [
      "Farmacologia",
      "Medicamentos",
      "Legislação Farmacêutica",
      "Gestão de Stock",
      "Boas Práticas de Farmácia",
      "Atendimento ao Cliente",
      "Segurança com Fármacos",
      "Manipulação de Medicamentos",
    ],
  },
  {
    id: "radiologia",
    slug: "radiologia",
    name: "Radiologia",
    category: "saude",
    categoryLabel: "Ensino Técnico Médio de Saúde",
    shortDescription: "Especialização em técnicas de imagiologia médica.",
    description:
      "Formação especializada em técnicas de imagiologia médica, radiografia, ecografia e ressonância magnética. Prepara técnicos para operar equipamentos de diagnóstico por imagem em hospitais e centros de saúde.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 20.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Técnico de Radiologia",
      "Especialista em Imagiologia",
      "Técnico de Ecografia",
      "Supervisor de Departamento",
      "Técnico de RM",
    ],
    requirements: [
      "Conclusão do 9º ano",
      "Conhecimento em Física",
      "Capacidade técnica",
    ],
    documents: [
      "Certificado do 9º ano",
      "Atestado médico",
      "Teste de tolerância à radiação",
      "Fotocópias de documentos",
    ],
    careerPath: "Técnico de Radiologia / Especialista em Imagiologia / Supervisor",
    highlights: [
      "Equipamento de radiologia moderno",
      "Simuladores de procedimentos",
      "Prática em hospitais",
      "Treinamento em protecção radiológica",
      "Certificação técnica reconhecida",
    ],
    topics: [
      "Física das Radiações",
      "Técnicas Radiográficas",
      "Ecografia",
      "Ressonância Magnética",
      "Protecção Radiológica",
      "Anatomia Radiológica",
      "Processamento de Imagens",
      "Segurança do Paciente",
    ],
  },
  {
    id: "fisioterapia",
    slug: "fisioterapia",
    name: "Fisioterapia",
    category: "saude",
    categoryLabel: "Ensino Técnico Médio de Saúde",
    shortDescription: "Formação em reabilitação e fisioterapia.",
    description:
      "Curso de Fisioterapia oferece formação em técnicas de reabilitação, exercício terapêutico e tratamento de lesões. Prepara técnicos para actuar em centros de reabilitação, hospitais e clínicas privadas.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 20.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Técnico de Fisioterapia",
      "Terapeuta de Reabilitação",
      "Especialista em Desporto",
      "Gestor de Clínica",
      "Supervisor Clínico",
    ],
    requirements: [
      "Conclusão do 9º ano",
      "Conhecimento em Biologia",
      "Aptidão física",
    ],
    documents: [
      "Certificado do 9º ano",
      "Atestado de capacidade física",
      "Referências de saúde",
      "Fotocópias de documentos",
    ],
    careerPath: "Técnico de Fisioterapia / Terapeuta Especializado / Gestor",
    highlights: [
      "Clínica de reabilitação equipada",
      "Equipamento de terapia moderno",
      "Prática com pacientes reais",
      "Supervisores especializados",
      "Oportunidades em desporto",
    ],
    topics: [
      "Anatomia e Fisiologia",
      "Patologia",
      "Técnicas Manuais",
      "Exercício Terapêutico",
      "Eletroterapia",
      "Traumatologia",
      "Desporto e Reabilitação",
      "Prática Clínica Supervisionada",
    ],
  },
  {
    id: "estomatologia",
    slug: "estomatologia",
    name: "Estomatologia",
    category: "saude",
    categoryLabel: "Ensino Técnico Médio de Saúde",
    shortDescription: "Especialização em saúde oral e estomatologia.",
    description:
      "Formação especializada em saúde oral, higiene dentária e assistência em procedimentos estomatológicos. Prepara técnicos para trabalhar em consultórios dentários, clínicas e hospitais.",
    classes: ["10ª", "11ª", "12ª", "13ª"],
    monthlyFee: "A partir de 20.000,00 Kz/mês",
    enrollmentFee: "20.000,00 Kz",
    duration: "4 anos",
    jobMarket: [
      "Técnico de Estomatologia",
      "Higienista Dental",
      "Assistente Dentário",
      "Gestor de Clínica Dentária",
      "Especialista em Reabilitação Oral",
    ],
    requirements: [
      "Conclusão do 9º ano",
      "Aptidão para trabalho preciso",
      "Interesse em saúde oral",
    ],
    documents: [
      "Certificado do 9º ano",
      "Atestado médico",
      "Vacinas obrigatórias",
      "Fotocópias de documentos",
    ],
    careerPath: "Técnico de Estomatologia / Higienista / Gestor de Clínica",
    highlights: [
      "Clínica dentária equipada",
      "Cadeiras e equipamento odontológico",
      "Prática com pacientes",
      "Supervisão de especialistas",
      "Mercado de trabalho estável",
    ],
    topics: [
      "Anatomia Dentária",
      "Higiene Oral",
      "Radiologia Dentária",
      "Técnicas de Limpeza",
      "Materiais Dentários",
      "Assistência em Cirurgia",
      "Prevenção de Doenças",
      "Educação em Saúde Oral",
    ],
  },
]

export function getCourseBySlug(slug: string): Course | undefined {
  return coursesData.find((course) => course.slug === slug)
}

export function getCoursesByCategory(category: "geral" | "tecnico" | "saude"): Course[] {
  return coursesData.filter((course) => course.category === category)
}

export function getAllCourses(): Course[] {
  return coursesData
}

export function getAllSlugs(): string[] {
  return coursesData.map((course) => course.slug)
}
